### ISSUE TITLE
Duplicate?

### ISSUE THREAD

**Issue by shawnholt** [mlutfy/ca.bidon.pcpteams#4]
I noticed this: https://github.com/veda-consulting/uk.co.vedaconsulting.pcpteams
is it a duplicate/rewrite or something different?

**Comment by mlutfy** [comment]
Indeed, it's mostly duplicate. I haven't checked in detail, but Parvez gave a nice talk about it at CiviCon Denver 2015. Some of the implementation details are interesting. For example, they use relationships to define the team members (whereas this module maintains a mysql table, but does not have a nice UI to manage teams).

I will add a comment to the README of this project. I still maintain minimally this extension because I have a client still using it (migration takes time), but folks who have to choose between one or the other should consider Veda's extension.
