### ISSUE TITLE
The duplicate pcpteams doesn't look ready at all

### ISSUE THREAD

**Issue by herbdool** [mlutfy/ca.bidon.pcpteams#5]
You've supported people use the other pcpteam extension https://github.com/veda-consulting/uk.co.vedaconsulting.pcpteams but it doesn't look ready. I tried to get more info there but no response yet. They don't have a README and the info.xml says its for 4.2, which is weird if you say it only came out last year.

**Comment by mlutfy** [comment]
It seems that, similarly to this extension, their development is probably around specific projects, so it can have ups and downs, although it does seem active lately. Nonetheless, I happy to continue maintaining this extension, and appreciate the patches that have been contributed.

I'll close this issue since there isn't any action to take. Feel free to ping me on Mattermost (https://chat.civicrm.org, I'm 'bgm'). In the odd chance you are near Montreal, join us at CiviCamp! https://civicrm.org/civicamp/montreal-2017 (Sept 27, 2017)
